### PR TITLE
refactor by using ghutils module

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by rvagg** [comment]
much good, thankee @ralphtheninja!

**Comment by ralphtheninja** [comment]
Oh hold on. I just created this commit on top of old master. Let me rebase.

**Comment by rvagg** [comment]
actually, this is not applying cleanly, can you rebase or something?

**Comment by ralphtheninja** [comment]
Working on it. See above :)

**Comment by ralphtheninja** [comment]
@rvagg There we go.

Q: I need some functionality to create releases and upload assets. Do you have that use case laying around somewhere or should that be a separate module or in this module? Technically releases belong to `repos`

reposapi

**Comment by rvagg** [comment]
@ralphtheninja no I don't have any examples of that, to be honest I've never even touched that API so I have no opinions, happy for you to make additions here or otherwise though

**Comment by ralphtheninja** [comment]
:+1:

**Pull request merged**
